variants:
- name: article
  context:
    mods: [article]
    content: |
      <p class="lede">A lead in paragraph to the main article or body of content.</p>

      The h-entry format is widely implemented for a variety of datestamped content on the web such as blog entries. Making sure that your published content follow microformat standards helps ensure it can be syndicated, read and understood across multiple platforms.