title: h-entry
context:
    title: Why use Microformats?
    summary: An article about Microformats
    author: Calum Ryan
    author_url: https://calumryan.com
    datetime: "2017-12-01T12:24:48-00:00"
    sections:
    - id: background
      title: Background
      content: |
        <p class="lede">24 ways is the advent calendar for web geeks. For twenty-four days each December we publish a daily dose of web design and development goodness to bring you all a little Christmas cheer.</p>

        Back in December 2005, Drew McLellan set up what he called "a festive blog" with a new article each day written by experts sharing their knowledge. Articles present ideas, techniques or experiences that you can take and apply to your own work. Code snippets, advice about business and clients, workflow and workshopping, design inspiration: 24 ways has it all.

        With over one hundred authors and almost two hundred articles, 24 ways is very proud to have become an annual fixture in the calendars of web geeks. Since 2005, 24 ways has always combined learning and sharing, both vital aspects of the continued strength of the web community. As Drew wrote, ‘There’s a lot of fun to be had in learning something that will impress those you work with – especially if then you can share what you know to everyone’s benefit.’
    - id: credits
      title: Credits
      content: |
        * 24 ways is brought to you by Perch and is built on [Perch Runway](https://grabaperch.com/?ref=24w01)
        * Produced by [Drew McLellan](http://allinthehead.com/), [Brian Suda](http://suda.co.uk/), [Anna Debenham](http://maban.co.uk/) and [Owen Gregory](http://fullcreammilk.co.uk/).
        * Designed by [Paul Robert Lloyd](https://paulrobertlloyd.com/).
        * Possible only with the help and dedication of [our authors](/authors/).
    - id: colophon
      title: Colophon
      content: |
        * Content managed with [Perch Runway](https://grabaperch.com/?ref=24w01).
        * Hosted by [Memset Dedicated Servers](https://www.memset.com/dedicated-servers/).
        * Standing on the shoulders of Varnish, Nginx, Apache, PHP, MySQL, Amazon S3 and CloudFront.
        * Type set in [Source Sans Pro](https://adobe-fonts.github.io/source-sans-pro/), [Source Serif Pro](https://adobe-fonts.github.io/source-serif-pro/) and [Source Code Pro](https://adobe-fonts.github.io/source-code-pro/) by Adobe.
        * Fonts served via [Google Fonts](https://fonts.google.com/).
        * [Minicons](http://www.webalys.com/minicons/) by Vincent Le Miogn.
        * [prism.js](https://github.com/leaverou/prism/) by Lea Verou.