collated: true
context:
  href: /
  title: "Why use Microformats?"
  datetime: "2017-11-11T00:00:00-00:00"
  excerpt_href: https://calumryan.com/
  content: Summary of the article, typically a short introduction that might also be used in the meta description tag