context:
  site:
    title: IndieWeb components
    handle: IndieWeb-components
    description: IndieWeb components, a front-end component library and styleguide including common Microformat data formats
    url: 
    feed: 
    theme_color: "#005ea5"
  theme:
    # Year hues = 348 - (4 × year increment)
    year: [348, 344, 340, 336, 332, 328, 324, 320, 316, 312, 308, 304, 300, 296, 292, 288]
    # Day hues = 360 - (7 × day increment)
    day: [360, 353, 346, 339, 332, 325, 318, 311, 304, 297, 290, 283, 276, 269, 262, 255, 248, 241, 234, 227, 220, 213, 206, 199]
