title: h-event
context:
  event_title: Homebrew Website Club
  event_start: "2017-12-01T12:24:48-00:00"
  event_end: "2017-12-01T12:24:48-00:00"
  event_location: The Hub
  event_summary: Get together and discuss all things IndieWeb-related.