default: topics
variants:
- name: topics
  context:
    title: "Topics"
    section: topics
    sections:
    - id: business
      title: "Business"
      mods: [topic]
      icon: topic-business
      content: |
        Where there's muck, there are clients, deliverables and contracts. Occasionally, there's brass. Here are articles on developing and improving relationships with clients; writing contracts and presenting your work; and encouraging success and avoiding failure.

        <a class="c-continue" href="/topic/business/">16 ways to improve your business</a>
    - id: code
      title: "Code"
      mods: [topic]
      icon: topic-code
      content: |
        Poetry? Not likely (though [Dan Cederholm wrote some doggerel](/2006/gravity-defying-page-corners/) back in 2006). Here are articles on hypertext markup language, its attributes and other minutiae; crafty ~~hacks~~ tips for your cascading style sheets; JavaScript legerdemain; and tinkering with application programming interfaces.

        <a class="c-continue" href="/topic/code/">45 ways to craft your code</a>
    - id: content
      title: "Content"
      mods: [topic]
      icon: topic-content
      content: |
        If code is our bread, then content is our butter. It's also been king for a while. A buttery smooth king. *[Ed: Mixing metaphors is inelegant, reveals a want of sophistication and causes confusion. Please stop.]* Whatever your preference, you'll find a wealth of useful information in our articles on copy, including its micro and macro aspects; content planning, strategy and management for sites big and small; as well as ideas on generating it.

        <a class="c-continue" href="/topic/content/">23 ways to sharpen your content</a>
    - id: design
      title: "Design"
      mods: [topic]
      icon: topic-design
      content: |
        Coloured crayons for felt-tip fairies. *[Ed: What has got into you? Sort this out.]* Alright, alright. Sheesh! There's much more to web design than mere surface. Markup minutiae and clever CSS techniques; art direction and photography; inspiration and theoretical application; layout and typography; systems of design and modularization; even music gets a look in.

        <a class="c-continue" href="/topic/design/">67 ways to enhance your design</a>
    - id: process
      title: "Process"
      mods: [topic]
      icon: topic-process
      content: |
        The great work of web, where it all comes together. Except when it doesn't and we need to re-examine the distance between how things are done and how they could and should be done. Advent articles revealed here cover managing projects, both business and personal; smoothing the flow of work; thoughts and techniques for working smarter and being better; and getting the most out of what we do.

        <a class="c-continue" href="/topic/process/">15 ways to hone your process</a>
    - id: ux
      title: "UX"
      mods: [topic]
      icon: topic-ux
      content: |
        Everything we make is made to be used: read, heard, pushed, swiped, clicked, followed, interacted with. Hard edges must be smoothed and blunt instruments sharpened. Users carry the web we've made with them and it must be ready to work on whatever they have to hand. From prototypes to product, from wireframe to web app, and all the research, analysis and testing in between, there are at least twenty-four ways.

        <a class="c-continue" href="/topic/ux/">34 ways to enhance your UX</a>
- name: archives
  context:
    title: "Archives"
    section: archives
    sections:
    - id: 2015
      title: "2015"
      content: |
        Ports and protocols were the name of the game, with swathes of the web switching to HTTPS connections. HTTP2 also started to gain adoption, and in doing so turned all we had learned about performance optimisation on its head. 24 ways saw increasing exploration of animation on the web, as well as renewed interest in accessibility, style guides and progressive enhancement.

        <a class="c-continue" href="/2015/">24 ways to impress your friends in 2015</a>
    - id: 2014
      title: "2014"
      content: |
        The web turned twenty-five and showed no sign of settling down in semi-detached suburbia. In October, HTML5 was released as a W3C Recommendation. Back in May, 24 ways was very excited and grateful to win the net award for best collaborative project – a huge thank you to all our authors, readers and supporters!

        <a class="c-continue" href="/2014/">24 ways to impress your friends in 2014</a>
    - id: 2013
      title: "2013"
      content: |
        Scourge of browser vendors everywhere, WaSP buzzed its last in March. Dave Shea's CSS Zen Garden celebrated its tenth anniversary in May, and Google Glass was released. Ever broad in its interests, 24 ways tamed Grunt, URLs and GitHub Pages, encouraged readers to write and publish books, and leavened all that with goodies on project management, web typography and SVG.

        <a class="c-continue" href="/2013/">24 ways to impress your friends in 2013</a>
    - id: 2012
      title: "2012"
      content: |
        During the same month that HTML5 was designated a Candidate Recommendation by the W3C, 24 ways covered issues of performance as part of responsive web design, CSS and preprocessing, responsive images (again) and design systems.

        <a class="c-continue" href="/2012/">24 ways to impress your friends in 2012</a>
    - id: 2011
      title: "2011"
      content: |
        In October, Steve Jobs died. The thorniest part of responsive web design, and an arena for many competing and dissenting voices was images. 24 ways tackled that and many other issues head on: conditional loading; front-end style guides; icon fonts; and the importance of side projects.

        <a class="c-continue" href="/2011/">24 ways to impress your friends in 2011</a>
    - id: 2010
      title: "2010"
      content: |
        In April, the iPad; in May, Ethan Marcotte's "Responsive Web Design" was published by A List Apart, and A Book Apart published <cite>HTML5 for Web Designers</cite> by Jeremy Keith; and then in June, the iPhone 4's Retina screen changed the web development landscape. 24 ways sprinkled its Christmas pudding with CSS3, including animations and transforms, a little light content strategy, and some thoughts about the web designer of tomorrow.

        <a class="c-continue" href="/2010/">24 ways to impress your friends in 2010</a>
    - id: 2009
      title: "2009"
      content: |
        A year when books were winning (Five Simple Steps published <cite>A Practical Guide to Designing for the Web</cite> by Mark Boulton and <cite>Designing with Web Standards</cite> by Jeffrey Zeldman and Ethan Marcotte reached its third edition) and the web was losing (Yahoo! closed Geocities). Significant progress was made with web fonts and HTML5, and 24 ways delivered the Christmas gifts again.

        <a class="c-continue" href="/2009/">24 ways to impress your friends in 2009</a>
    - id: 2008
      title: "2008"
      content: |
        This year saw Apple's App Store open, and the release of Android 1.0 and Google Chrome 1.0. Taking all that in its stride, 24 ways brought its seasonal perspective to bear on business, with articles on project management, the path from design to development, how to charm clients, and killer contracts. Also, a first look at modular layout systems. Pulse, meet finger.

        <a class="c-continue" href="/2008/">24 ways to impress your friends in 2008</a>
    - id: 2007
      title: "2007"
      content: |
        Apple launched the iPhone in June; Amazon released the Kindle in November — a big year. At three, 24 ways was as diverse as ever, taking a detailed look at font stacks, website performance, working with clients and markup.

        <a class="c-continue" href="/2007/">24 ways to impress your friends in 2007</a>
    - id: 2006
      title: "2006"
      content: |
        In March, the first tweets were tweeted; in August, jQuery 1.0 appeared. In its second year, 24 ways wrote responsible JavaScript and hinted at a mobile web, although mobile phones didn't yet have proper browsers. Using CSS3 in client work was still a pipedream. And in October, IE7 was officially released by Microsoft — no words.

        <a class="c-continue" href="/2006/">24 ways to impress your friends in 2006</a>
    - id: 2005
      title: "2005"
      content: |
        It all started here, in the heady days of Web 2.0. Ajax was the first new browser technology we'd seen in years, and combined with a new breed of libraries such as Prototype, it kick-started the JavaScript renaissance.

        <a class="c-continue" href="/2005/">24 ways to impress your friends in 2005</a>
- name: authors
  context:
    title: "Authors"
    section: authors
    sections:
    - id: a
      title: "A"
      component: listing--authors
      config:
        mods: [authors]
        component: author
        items:
        - author: John Allsopp
        - author: Rachel Andrew
        - author: Paul Annett
    - id: b
      title: "B"
      component: listing--authors
      config:
        mods: [authors]
        component: author
        items:
        - author: Ashley Baxter
        - author: Darren Beale
        - author: Gavin Bell
        - author: Frances Berriman
        - author: Kimberly Blessing
        - author: Paul Boag
        - author: Ben Bodien
        - author: Jina Bolton
        - author: Mark Boulton
        - author: Cennydd Bowles
        - author: Ross Bruniges
        - author: Andy Budd
        - author: Heather Burns
    - id: c
      title: "C"
      component: listing--authors
      config:
        mods: [authors]
        component: author
        items:
        - author: Dan Cederholm
        - author: Andy Clarke
        - author: Geri Coady
        - author: Dave Collins
        - author: Simon Collison
        - author: Rebecca Cottrell
        - author: Chris Coyier
        - author: Matt Curry
